Repository caponetto/backstage-plugins, pull requests merged in 2023-11, with the labels that each got.

#23 feat: add backend for getting work flows from data index service
  app-config.yaml
  plugins/orchestrator-backend/README.md
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/helpers/errorBuilder.ts
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-backend/src/types/apiResponse.ts
  plugins/orchestrator-backend/src/types/backendExecCtx.ts
  plugins/orchestrator-backend/src/types/constants.ts
  plugins/orchestrator-common/config.d.ts
  yarn.lock
Labels: not-in-KOGITO-9778

#21 feat: issue FLPATH-591 - Add assessment workflow type and display outputs
  packages/app/src/App.tsx
  plugins/orchestrator-backend/src/catalog/OrchestratorEntityProvider.ts
  plugins/orchestrator-backend/src/catalog/index.ts
  plugins/orchestrator-backend/src/provider/OrchestratorEntityProvider.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-common/src/constants.ts
  plugins/orchestrator-common/src/types.ts
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/OrchestratorPage/OrchestratorPage.tsx
  plugins/orchestrator/src/components/ScaffolderTemplateCard/OrchestratorScaffolderTemplateCard.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionsListComponent/WorkflowDefinitionsListComponent.tsx
  plugins/orchestrator/src/components/WorkflownstancesViewerPage/AssessmentResultViewer.tsx
  plugins/orchestrator/src/components/WorkflownstancesViewerPage/WorkflowInstancesViewerPage.tsx
  yarn.lock
Labels: not-in-KOGITO-9778

#25 feat: optional config
  app-config.yaml
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/WorkflowService.ts
  plugins/orchestrator-common/config.d.ts
  plugins/orchestrator/README.md
Labels: not-in-KOGITO-9778

#38 fix(orchestrator): make the port config optional
  plugins/orchestrator-backend/config.d.ts
  plugins/orchestrator-backend/src/provider/OrchestratorEntityProvider.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
Labels: cherry-pick 🍒

#35 feat(orchestrator): handle assessment workflow and make optional the workflowsSource config
  plugins/orchestrator-backend/config.d.ts
  plugins/orchestrator-backend/src/provider/OrchestratorEntityProvider.ts
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/WorkflowService.ts
  plugins/orchestrator-common/src/constants.ts
  plugins/orchestrator-common/src/types.ts
  plugins/orchestrator/README.md
  plugins/orchestrator/package.json
  plugins/orchestrator/src/components/OrchestratorPage/OrchestratorPage.tsx
  plugins/orchestrator/src/components/ScaffolderTemplateCard/OrchestratorScaffolderTemplateCard.tsx
  plugins/orchestrator/src/components/WorkflowDefinitionsListComponent/WorkflowDefinitionsListComponent.tsx
  plugins/orchestrator/src/components/WorkflownstancesViewerPage/AssessmentResultViewer.tsx
  plugins/orchestrator/src/components/WorkflownstancesViewerPage/WorkflowInstancesViewerPage.tsx
Labels: cherry-pick 🍒

#31 feat(orchestrator): orchestrator plugin entry page & workflows table
  plugins/orchestrator/package.json
  plugins/orchestrator/src/__fixtures__/fakeProcessInstance.ts
  plugins/orchestrator/src/__fixtures__/fakeWorkflowItem.ts
  plugins/orchestrator/src/api/MockOrchestratorClient.ts
  plugins/orchestrator/src/components/Router.tsx
  plugins/orchestrator/src/components/next/BaseOrchestratorPage.tsx
  plugins/orchestrator/src/components/next/OrchestratorPage.stories.tsx
  plugins/orchestrator/src/components/next/OrchestratorPage.tsx
  plugins/orchestrator/src/components/next/WorkflowsTable.stories.tsx
  plugins/orchestrator/src/components/next/WorkflowsTable.tsx
  plugins/orchestrator/src/routes.ts
  yarn.lock
Labels: not-in-KOGITO-9778

#36 feat: introduced the workflows/overview endpoint
  plugins/orchestrator-backend/src/service/SonataFlowService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-common/src/types.ts
Labels: not-in-KOGITO-9778

#39 feat(orchestrator): add backend endpoint for getting workflows from data index service
  plugins/orchestrator-backend/config.d.ts
  plugins/orchestrator-backend/dist-dynamic/package.json
  plugins/orchestrator-backend/dist-dynamic/yarn.lock
  plugins/orchestrator-backend/package.json
  plugins/orchestrator-backend/src/helpers/errorBuilder.ts
  plugins/orchestrator-backend/src/service/DataIndexService.ts
  plugins/orchestrator-backend/src/service/router.ts
  plugins/orchestrator-backend/src/types/apiResponse.ts
  plugins/orchestrator-backend/src/types/backendExecCtx.ts
  plugins/orchestrator-backend/src/types/constants.ts
  plugins/orchestrator/README.md
  yarn.lock
Labels: cherry-pick 🍒

#41 chore(orchestrator): implement the WorkflowViewerFormatter
  plugins/orchestrator/src/dataFormatters/DataFormatter.ts
  plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.test.ts
  plugins/orchestrator/src/dataFormatters/WorkflowOverviewFormatter.ts
Labels: not-in-KOGITO-9778, UX
